root: /
permalink: /:year/:month/:day/:title/
markdown: rdiscount
pygments: true
server_port: 4000
baseurl:    /
url: http://localhost:4000
paginate: 5
recent_posts: 5
exclude: ["_sass", Rakefile", "config.rb", "config.ru"]