root: /
safe: true
pygments: true
permalink: /:year/:month/:day/:title/
markdown: rdiscount
server_port: 4000
baseurl:    /
url: http://codigocomestible.com
paginate: 5
recent_posts: 5
exclude: ["_sass", "Rakefile", "config.rb", "config.ru"]